# Generated by Django 4.2 on 2023-05-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
