# Generated by Django 4.2 on 2023-05-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_popularitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('imageurl', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=800)),
            ],
        ),
    ]
