# Generated by Django 4.2 on 2023-05-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DinnerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LunchItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
