# Generated by Django 4.2 on 2023-05-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_breakfastitems_dinneritems_lunchitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
