# Generated by Django 4.2 on 2023-05-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
